### ISSUE TITLE
Rename to Gonville

### ISSUE THREAD

**Issue by ronyeh** [rvilarl/gonville#1]
Hello @rvilarl 

I reached out to Simon Tatham over email and he told me that it is okay for us to name this font "Gonville" for the purposes of using it in VexFlow. At some point he will make his font generation scripts output an official build of Gonville that is SMuFL compliant, and then we can just swap in the official build at that time.

Can you produce a `Gonville.otf` and `Gonville.woff2` with the correct font name?

Thanks!

**Comment by ronyeh** [comment]
https://github.com/rvilarl/gonvillesmufl/blob/2cd2f1ea993f5736ee345e9968417777b0624313/gonville2smufl.py#L305-L311


It probably would be a good thing to add the original designer's name ( Simon Tatham ) to the copyright line, even though his original license is extremely permissive ("without restriction").

We should also include the original website for Gonville in the copyright text.
https://www.chiark.greenend.org.uk/~sgtatham/gonville/

**Comment by rvilarl** [comment]
I am not keen on setting license owner on behalf of other people. I have a suggestion. Please start a vexflow/gonville with the work I did. Licensed to the organization  and a clear statement that once the original author releases a SMuFL variant this repository will be frozen. I think that it makes more sense to have the font in the organization rather than in my user.

**Comment by ronyeh** [comment]
Sounds good! I will start vexflow/gonville, and will try to work with Simon to get an official SMuFL release of his font. In the meantime, we will use your patch.
